DROP TABLE IF EXISTS Tweet;
CREATE TABLE Tweet (
    Id VARCHAR(1023) NOT NULL,
    Author VARCHAR(1023) NOT NULL,
    CommitedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    Content VARCHAR(1023) NOT NULL,
    Count INT(64) NOT NULL,
    CreatedAt TIMESTAMP NOT NULL,
    Favos VARCHAR(1023) NOT NULL,
    Sort INT(64) NOT NULL,
    UpdatedAt TIMESTAMP NOT NULL,
    ShardCreatedAt INT(64) NOT NULL,
    PRIMARY KEY (Id)
);

CREATE INDEX TweetSortAsc
ON Tweet (
	Sort
);